# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import mykvserver_pb2 as mykvserver__pb2


class KVServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Join = channel.unary_unary(
        '/KVServer/Join',
        request_serializer=mykvserver__pb2.JoinRequest.SerializeToString,
        response_deserializer=mykvserver__pb2.JoinResponse.FromString,
        )
    self.PutRequest = channel.unary_unary(
        '/KVServer/PutRequest',
        request_serializer=mykvserver__pb2.PutMessage.SerializeToString,
        response_deserializer=mykvserver__pb2.PutReply.FromString,
        )
    self.GetRequest = channel.unary_unary(
        '/KVServer/GetRequest',
        request_serializer=mykvserver__pb2.GetMessage.SerializeToString,
        response_deserializer=mykvserver__pb2.GetReply.FromString,
        )
    self.DelRequest = channel.unary_unary(
        '/KVServer/DelRequest',
        request_serializer=mykvserver__pb2.DelMessage.SerializeToString,
        response_deserializer=mykvserver__pb2.DelReply.FromString,
        )
    self.VoteRequest = channel.unary_unary(
        '/KVServer/VoteRequest',
        request_serializer=mykvserver__pb2.VoteMessage.SerializeToString,
        response_deserializer=mykvserver__pb2.VoteReply.FromString,
        )
    self.HeartBeat = channel.unary_unary(
        '/KVServer/HeartBeat',
        request_serializer=mykvserver__pb2.HBMessage.SerializeToString,
        response_deserializer=mykvserver__pb2.HBReply.FromString,
        )
    self.SpreadLog = channel.unary_unary(
        '/KVServer/SpreadLog',
        request_serializer=mykvserver__pb2.LogMessage.SerializeToString,
        response_deserializer=mykvserver__pb2.LogReply.FromString,
        )
    self.SpreadCommit = channel.unary_unary(
        '/KVServer/SpreadCommit',
        request_serializer=mykvserver__pb2.CommitMessage.SerializeToString,
        response_deserializer=mykvserver__pb2.CommitReply.FromString,
        )


class KVServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Join(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PutRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DelRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VoteRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HeartBeat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SpreadLog(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SpreadCommit(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KVServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Join': grpc.unary_unary_rpc_method_handler(
          servicer.Join,
          request_deserializer=mykvserver__pb2.JoinRequest.FromString,
          response_serializer=mykvserver__pb2.JoinResponse.SerializeToString,
      ),
      'PutRequest': grpc.unary_unary_rpc_method_handler(
          servicer.PutRequest,
          request_deserializer=mykvserver__pb2.PutMessage.FromString,
          response_serializer=mykvserver__pb2.PutReply.SerializeToString,
      ),
      'GetRequest': grpc.unary_unary_rpc_method_handler(
          servicer.GetRequest,
          request_deserializer=mykvserver__pb2.GetMessage.FromString,
          response_serializer=mykvserver__pb2.GetReply.SerializeToString,
      ),
      'DelRequest': grpc.unary_unary_rpc_method_handler(
          servicer.DelRequest,
          request_deserializer=mykvserver__pb2.DelMessage.FromString,
          response_serializer=mykvserver__pb2.DelReply.SerializeToString,
      ),
      'VoteRequest': grpc.unary_unary_rpc_method_handler(
          servicer.VoteRequest,
          request_deserializer=mykvserver__pb2.VoteMessage.FromString,
          response_serializer=mykvserver__pb2.VoteReply.SerializeToString,
      ),
      'HeartBeat': grpc.unary_unary_rpc_method_handler(
          servicer.HeartBeat,
          request_deserializer=mykvserver__pb2.HBMessage.FromString,
          response_serializer=mykvserver__pb2.HBReply.SerializeToString,
      ),
      'SpreadLog': grpc.unary_unary_rpc_method_handler(
          servicer.SpreadLog,
          request_deserializer=mykvserver__pb2.LogMessage.FromString,
          response_serializer=mykvserver__pb2.LogReply.SerializeToString,
      ),
      'SpreadCommit': grpc.unary_unary_rpc_method_handler(
          servicer.SpreadCommit,
          request_deserializer=mykvserver__pb2.CommitMessage.FromString,
          response_serializer=mykvserver__pb2.CommitReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'KVServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
